image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Albedo Signer"
  - init: |
      cd squirtle
      npm run compile
    command: |
      cd squirtle
      npm run bin
      cd ../
      rm -rf squirtle
      clear
      cd client
      npm run start
  - name: Futurenet
    init: | 
      docker pull stellar/quickstart:soroban-dev
    command: |
      docker run --rm -it \
      --name stellar \
      -p 8000:8000 \
      stellar/quickstart:soroban-dev \
      --futurenet \
      --enable-soroban-rpc
  - name: CLI – Futurenet
    env:
      # This might should be set by the user. Also needs to be actually exist as a funded account on the futurenet
      SOROBAN_SECRET_KEY: SDUOO3L7CNFXNNWSRSUCEJDKY5CLBZRI23UF6ZNXD23W5NGKJWVMGR7O
      SOROBAN_RPC_URL: "http://localhost:8000/soroban/rpc"
      SOROBAN_NETWORK_PASSPHRASE: "Test SDF Future Network ; October 2022"
    command: |
      clear
  - name: CLI – Sandbox
    init: |
      cargo clean
      cargo fetch
      make build
      cargo test -p soroban-hello-world-contract
    command: |
      gp open README.md
      clear

vscode:
  extensions:
    - vadimcn.vscode-lldb
    - matklad.rust-analyzer

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

ports:
  - name: Horizon + RPC endpoint
    port: 8000
    visibility: public
    onOpen: ignore
  - name: Stellar Quest
    port: 3000
    visibility: public
    onOpen: ignore
  - port: 4226
    visibility: private
    onOpen: ignore
